// server/complianceGuard.js
//
// Deterministic compliance layer for MutualMind.
//
// Two responsibilities:
//   1. FIXED, code-owned response text for compliance-triggering intents —
//      this text is NEVER generated by the LLM, so it cannot drift, be
//      jailbroken, or be worded inconsistently across requests.
//   2. A post-response guard that scans EVERY LLM reply (even ones the
//      classifier considered safe) for advice-like language, as
//      defense-in-depth. Classifiers can miss things; this catches
//      leakage regardless of why it happened.
//
// This directly addresses the top finding of the prior audit
// (MutualMind-Engineering-Deep-Dive.md, Phase 7/9/11): "the recommendation
// ban is enforced only by a prompt string, with zero server-side check."

import { INTENTS } from './intentClassifier.js'

export const ADVISOR_REDIRECT_URL = 'https://arthvruksh.com/'

export const COMPLIANCE_DISCLAIMER =
  "I'm designed to provide educational information and factual explanations about financial concepts. I'm not authorised to recommend or suggest investment products, fund selections, or personalised investment decisions. For personalised guidance based on your goals and risk profile, please connect with a SEBI-registered / AMFI-registered advisor at " +
  ADVISOR_REDIRECT_URL + "."

export const OUT_OF_SCOPE_MESSAGE =
  "I'm MutualMind — I only cover mutual funds and the share-market basics needed to understand them (SIP, NAV, taxation, risk, fund categories, SEBI/AMFI regulation, and related concepts). That question is outside my scope, so I can't help with it here. Happy to explain anything about mutual funds, though!"

// Per-intent follow-up guidance shown alongside COMPLIANCE_DISCLAIMER,
// suggesting the kind of educational question the user CAN ask instead —
// mirrors the spec's "answer the educational part only" instruction.
export const EDUCATIONAL_REDIRECT_HINTS = {
  [INTENTS.FUND_RECOMMENDATION]:
    'I can, however, explain what factors are generally used to evaluate or compare mutual fund categories — for example, expense ratio, risk level (Riskometer), portfolio composition, and consistency over time. Ask me about any of those and I\'ll explain in depth.',
  [INTENTS.PORTFOLIO_REVIEW]:
    'I can explain the general concepts used in portfolio construction instead — for example, what diversification means, how equity/debt/hybrid allocation works, or how to think about risk versus time horizon.',
  [INTENTS.INVESTMENT_RECOMMENDATION]:
    'I can explain the trade-offs behind common investment decisions — for example, how SIP and lump sum work differently, what asset allocation means, or how taxation differs across fund categories. Ask me about the concept and I\'ll walk you through it.',
  [INTENTS.RISK_PROFILING]:
    'I can explain what risk profiling means in general — the categories used (conservative, moderate, aggressive), and the kinds of risk (market, credit, interest rate, liquidity) that go into that assessment.',
  [INTENTS.ADVICE_SEEKING]:
    'I am happy to explain the underlying concept in detail — just ask me "what is..." or "how does... work" and I\'ll cover it thoroughly.',
}

/**
 * Build the deterministic compliance-first message for a compliance-
 * triggering intent. This text is returned to the user VERBATIM — it is
 * never passed through or rewritten by the LLM.
 */
export function buildComplianceResponse(intent) {
  const hint = EDUCATIONAL_REDIRECT_HINTS[intent] || EDUCATIONAL_REDIRECT_HINTS[INTENTS.ADVICE_SEEKING]
  return `${COMPLIANCE_DISCLAIMER}\n\n${hint}`
}

// --- Post-response guard (defense in depth) --------------------------------
//
// Even with the classifier intercepting known advice-seeking phrasing before
// the LLM is called, the LLM can still volunteer advice-like language on an
// otherwise-legitimate educational question (e.g. answering "difference
// between two fund categories" by slipping in "Category A is generally
// better for you"). This scanner runs on every AI reply, no exceptions.

const BANNED_PHRASE_PATTERNS = [
  /\bi\s+(recommend|suggest)\b/i,
  /\byou\s+should\s+(invest|buy|sell|choose|pick|switch)\b/i,
  /\bthis\s+(fund|scheme|amc)\s+(is|will)\s+(the\s+best|better|outperform)/i,
  /\b(is|will\s+be)\s+the\s+best\s+(fund|scheme|choice|option)\b/i,
  /\bi'?d\s+(recommend|suggest|advise)\b/i,
  /\bmy\s+(recommendation|advice|suggestion)\s+(is|would\s+be)\b/i,
  /\byou\s+should\s+definitely\b/i,
  /\bguaranteed\s+returns?\b/i,
  /\bwill\s+(definitely|certainly)\s+(grow|increase|outperform|beat)\b/i,
]

/**
 * Scan a candidate reply (already generated by the LLM) for advice-like
 * language that should never reach the user. Returns { safe, matched }.
 */
export function scanForBannedLanguage(replyText) {
  if (!replyText) return { safe: true, matched: null }
  for (const re of BANNED_PHRASE_PATTERNS) {
    if (re.test(replyText)) {
      return { safe: false, matched: re.source }
    }
  }
  return { safe: true, matched: null }
}

// Fixed fallback used when the guard catches a banned phrase — logged
// server-side and returned to the user instead of the flagged text. This is
// deliberately generic (not a rewritten version of the flagged content)
// because the whole point of catching it here is that we do not trust the
// model's output on this turn.
export const GUARD_TRIGGERED_FALLBACK =
  "I need to rephrase that answer to keep it strictly educational. " +
  COMPLIANCE_DISCLAIMER +
  " Please ask me about the concept itself (for example, \"what is...\" or \"how does... work\") and I'll explain it in detail."
